name: Update champions

on:
  schedule:
    - cron: "0 7 * * *" # каждый день в 03:00 UTC
  workflow_dispatch: # запуск руками

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install deps
        run: npm ci

      - name: Import champions
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
        run: node scripts/import-champions.mjs

      - name: Import CN history
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
        run: node scripts/import-cn-history.mjs
